# Generated by Django 3.0.5 on 2021-02-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0003_yearlytable_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlytable',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='yearlytable',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='yearlytable',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='yearlytable',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
